apiVersion: v1
kind: Service
metadata:
  name: orders
spec:
  type: NodePort
  ports:
  - name: "orders-service"
    port: 6000
    targetPort: 80
  selector:
    app: orders
  
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: orders
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - image: icplab/orders:1
        name: orders
        imagePullPolicy: IfNotPresent
